-- WorkflowCore 持久化表（第三方存储结构，不属于 EF 模型）。
-- 对应 WfDbContext（Flow/EIMSNext.Flow.Service/WfDbContext.cs）的 WorkflowInstance /
-- ExecutionPointer / EventSubscription / Event / ExecutionError / ScheduledCommand。
-- 形状以 WorkflowCore 的 store 契约为准：ExecutionError / ScheduledCommand 的主键是
-- 引擎自增 bigint，其余是 text，不要按项目的 string Id 约定「统一」。

-- WorkflowCore IDs are opaque engine identifiers. New store-only IDs use bigint.
CREATE TABLE "WorkflowInstance" (
    "Id" text PRIMARY KEY,
    "WorkflowDefinitionId" text,
    "Version" integer NOT NULL,
    "Description" text,
    "Reference" text,
    "NextExecution" bigint,
    "Status" integer NOT NULL,
    "Data" jsonb,
    "CreateTime" timestamptz NOT NULL,
    "CompleteTime" timestamptz
);

-- 执行指针拆行存储：旧实现把整个指针数组塞进 WorkflowInstance 的单个 jsonb 列，
-- 每次 PersistWorkflow 全量重写，写放大随流程长度线性增长。拆成每指针一行后，
-- PostgreSqlPersistenceProvider 按指针差量同步（增/删/改各自落行），引擎每步只前进
-- 少量指针。WorkflowId 级联删除，Purger 删实例时无需再清指针。
CREATE TABLE "ExecutionPointer" (
    "Id" text PRIMARY KEY,
    "WorkflowId" text NOT NULL REFERENCES "WorkflowInstance" ("Id") ON DELETE CASCADE,
    "StepId" integer NOT NULL,
    "Active" boolean NOT NULL,
    "SleepUntil" timestamptz,
    "PersistenceData" jsonb,
    "StartTime" timestamptz,
    "EndTime" timestamptz,
    "EventName" text,
    "EventKey" text,
    "EventPublished" boolean NOT NULL,
    "EventData" jsonb,
    "ExtensionAttributes" jsonb,
    "StepName" text,
    "RetryCount" integer NOT NULL,
    "Children" jsonb,
    "ContextItem" jsonb,
    "PredecessorId" text,
    "Outcome" jsonb,
    "Status" integer NOT NULL,
    "Scope" jsonb
);

CREATE TABLE "EventSubscription" (
    "Id" text PRIMARY KEY,
    "WorkflowId" text,
    "StepId" integer NOT NULL,
    "ExecutionPointerId" text,
    "EventName" text,
    "EventKey" text,
    "SubscribeAsOf" timestamptz NOT NULL,
    "SubscriptionData" jsonb,
    "ExternalToken" text,
    "ExternalWorkerId" text,
    "ExternalTokenExpiry" timestamptz
);

CREATE TABLE "Event" (
    "Id" text PRIMARY KEY,
    "EventName" text,
    "EventKey" text,
    "EventData" jsonb,
    "EventTime" timestamptz NOT NULL,
    "IsProcessed" boolean NOT NULL
);

CREATE TABLE "ExecutionError" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ErrorTime" timestamptz NOT NULL,
    "WorkflowId" text,
    "ExecutionPointerId" text,
    "Message" text
);

CREATE TABLE "ScheduledCommand" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CommandName" text NOT NULL,
    "Data" text NOT NULL,
    "ExecuteTime" bigint NOT NULL
);
