-- WorkflowCore IDs are opaque engine identifiers. New store-only IDs use bigint.
CREATE TABLE "WorkflowInstance" (
    "Id" text PRIMARY KEY,
    "WorkflowDefinitionId" text,
    "Version" integer NOT NULL,
    "Description" text,
    "Reference" text,
    "ExecutionPointers" jsonb,
    "NextExecution" bigint,
    "Status" integer NOT NULL,
    "Data" jsonb,
    "CreateTime" timestamptz NOT NULL,
    "CompleteTime" timestamptz
);

CREATE TABLE "EventSubscription" (
    "Id" text PRIMARY KEY,
    "WorkflowId" text,
    "StepId" integer NOT NULL,
    "ExecutionPointerId" text,
    "EventName" text,
    "EventKey" text,
    "SubscribeAsOf" timestamptz NOT NULL,
    "SubscriptionData" jsonb,
    "ExternalToken" text,
    "ExternalWorkerId" text,
    "ExternalTokenExpiry" timestamptz
);

CREATE TABLE "Event" (
    "Id" text PRIMARY KEY,
    "EventName" text,
    "EventKey" text,
    "EventData" jsonb,
    "EventTime" timestamptz NOT NULL,
    "IsProcessed" boolean NOT NULL
);

CREATE TABLE "ExecutionError" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ErrorTime" timestamptz NOT NULL,
    "WorkflowId" text,
    "ExecutionPointerId" text,
    "Message" text
);

CREATE TABLE "ScheduledCommand" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CommandName" text NOT NULL,
    "Data" text NOT NULL,
    "ExecuteTime" bigint NOT NULL
);
