<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>EIMSNext Team</Authors>
    <Version>1.1.0.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Composition.AttributedModel" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Core\EIMSNext.Entities\EIMSNext.Entities.csproj" />
    <ProjectReference Include="..\EIMSNext.Identity.Abstractions\EIMSNext.Identity.Abstractions.csproj" />
    <ProjectReference Include="..\EIMSNext.Feishu\EIMSNext.Feishu.csproj" />
    <ProjectReference Include="..\..\Core\EIMSNext.Core\EIMSNext.Core.csproj" />
    <ProjectReference Include="..\..\Core\EIMSNext.Mef\EIMSNext.Mef.csproj" />
  </ItemGroup>
</Project>
