<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>EIMSNext Team</Authors>
    <Version>1.1.0.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CloudNative.CloudEvents" />
    <PackageReference Include="CloudNative.CloudEvents.SystemTextJson" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Core\EIMSNext.Common\EIMSNext.Common.csproj" />
    <ProjectReference Include="..\..\Core\EIMSNext.Core\EIMSNext.Core.csproj" />
    <ProjectReference Include="..\..\Core\EIMSNext.Entities\EIMSNext.Entities.csproj" />
    <ProjectReference Include="..\EIMSNext.Notification.Contracts\EIMSNext.Notification.Contracts.csproj" />
  </ItemGroup>
</Project>
