<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>EIMSNext Team</Authors>
    <Version>1.1.0.0</Version>
    <AssemblyName>EIMSNext.File</AssemblyName>
    <RootNamespace>EIMSNext.File</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Core\EIMSNext.Core\EIMSNext.Core.csproj" />
    <ProjectReference Include="..\..\Core\EIMSNext.Entities\EIMSNext.Entities.csproj" />
    <ProjectReference Include="..\EIMSNext.File.Contracts\EIMSNext.File.Contracts.csproj" />
    <ProjectReference Include="..\..\Core\EIMSNext.Storage\EIMSNext.Storage.csproj" />
  </ItemGroup>
</Project>
